[package]
name = "seismic-wave-modeller"
edition = "2024"
[dependencies]
colorgrad = { version = "0.8.0", features = ["preset"] }
ndarray = { version = "0.17.1", features = ["rayon"] }
plotters = "0.3.7"
rayon = "1.11.0"
